dist: trusty
sudo: required
language: php
php:
- 5.6
- 7.0
- 7.1
- hhvm-3.18
before_script:
- curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
- travis_retry composer install
script:
- if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then 
    ./vendor/bin/phpunit;
  else
    ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml;
  fi  
after_success:
- if ! [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then 
    travis_retry php vendor/bin/php-coveralls;
  fi  
notifications:
  slack:
    secure: S/OnTLCACoEB/LHzN95rAM5xcGTKCNviVin5VawsTJZ2RMUa4J9yBmZpGpk+3u/pn83dmPZ2b2V7A3VCuuthHY67EFJ8c6QcoeGQbs9XzBYqEiwtywTwWGXWfoAZ5nFPqNRS9AgwNitPjzEJh+uiMVcYW7foroPU6lvM5PizTDI=
